server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.215.118:3306/shirolearn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: opportunity

  redis:
    host: 106.14.215.118
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
    password: opportunity

#配置实体类的位置
mybatis-plus:
  type-aliases-package: com.it.wei.model
  mapper-locations: classpath*:mapper/*.xml
